
# Project
site_name: OSBA Regulatory Monitor
site_url: https://eacg-gmbh.github.io/osba-regulatory-monitor/
site_description: >-
  Stellt eine Uebersicht an Regularien sowie deren Wirkung auf die Software-Entwicklung vor 
site_author: OSBA Security Workgroup 
# Repository
repo_url: https://github.com/eacg-gmbh/osba-regulatory-monitor
edit_uri: ""    # prevents the edit button to link into URL

# Copyright
copyright: Copyright &copy; 2025 <a href="https://osb-alliance.de/impressum">OSBA WG Security</a>

nav:
  - Hintergrund: 
    - 'index.md'
    - Mitarbeit: 'adding.md'
    - Gestaltungsvorgaben: 'guidelines.md'
  - EU Regularien: 
    - EU Cyber Resilience Act: 'cra.md'
    - EU NIS2 directive: 'nis2.md'
    - Proudktsicherheit: 'malware.md'
    - snippets scanning: 'snippets.md'
  - Non-EU: 'non-eu.md'
  - About: 
    - 'about.md'
    - Changelog: '../CHANGELOG.md'


theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font: false # set false, to comply with data privacy (google fonts)
  #  text: Open Sans
  #  code: Courier
  logo: assets/osba-logo-claim.svg
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    # - navigation.expand 
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  plugins:
    - tags
    
extra:
  homepage: https://www.osb-alliance.de
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users find what they're searching for. With your consent, you're helping us to make our documentation better. 
    cookies:
      analytics: 
        name: Google Analytics
        checked: false
    actions:
      - accept
      - manage
      - reject
  #version:
  #  provider: mike
  #  default: stable
  analytics:
    provider: google
    property: 
  feedback:
    title: War diese Seite hilfreich?
    ratings:
      - icon: material/emoticon-happy-outline
        name: Ja, sehr!
        data: 1
        note: >-
         Danke fuer das Feedback!
      - icon: material/emoticon-sad-outline
        name: Naja, die Seite koennte verbessert werden
        data: 0
        note: >-
         Danke fuer das Feedback! Hilf uns besser zu werden und <a href="https://www.osb-alliance.de/kontakt" target="_blank" rel="noopener">sage uns</a>, was wir besser machen koennen.
  social:

extra_javascript:
  - assets/feedback.js
